M1 plugin player
qualabs/delightful_player pull request #2
Opened 2022-09-07 17:02 UTC by rodrigog-qualabs

Adds the player with the divs ir order to put colors inside them.

2022-09-07 17:04 UTC, paoopintos approved these changes

2022-09-07 17:08 UTC, Leonela27 requested changes
Queremos que el video de ejemplo quede en la main?
Queremos pisar todo el index que generó el template? o solo mergearle lo que son nuestros cambios ? o tener un 2do index ?

2022-09-07 17:17 UTC, Leonela27 approved these changes

2022-09-12 17:10 UTC, Leonela27 reviewed
el video es el de bbb? se puede renombrar?

2022-09-12 18:24 UTC, paoopintos commented
> el video es el de bbb? se puede renombrar?

si, puse el de bbb como primer ejemplo. lo que hice fue cambiar los nombres del selector para saber qué video es, en vez de example 1, 2, 3 como estaba antes.

2022-09-12 18:26 UTC, paoopintos approved these changes

2022-09-12 19:38 UTC, paoopintos approved these changes

2022-09-12 19:39 UTC, merged